# Generated by Django 3.2.5 on 2023-11-21 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_archive'),
    ]

    operations = [
        migrations.CreateModel(
            name='RangeYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_year', models.IntegerField()),
                ('second_year', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='archive',
            name='date',
            field=models.CharField(max_length=500),
        ),
    ]
